### ISSUE TITLE
OpenAI API key not found

### ISSUE THREAD

**Issue by jiechen257** [jiechen257/langchain-demo#1]
```shell
$ npm run start     

> langchain-ts-starter@1.0.0 start
> tsx -r dotenv/config src/index.ts

Error: OpenAI API key not found
    at OpenAIChat (/Users/abm/Documents/personal/personal-project/langchain-demo/node_modules/.pnpm/langchain@0.0.39/node_modules/langchain/src/llms/openai-chat.ts:125:13)
    at OpenAI (/Users/abm/Documents/personal/personal-project/langchain-demo/node_modules/.pnpm/langchain@0.0.39/node_modules/langchain/src/llms/openai.ts:143:14)
    at <anonymous> (/Users/abm/Documents/personal/personal-project/langchain-demo/src/index.ts:6:15)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
```

**Comment by jiechen257** [comment]
Change the name of the `.env.example` file to `.env`
