### ISSUE TITLE
ReferenceError: Headers is not defined

### ISSUE THREAD

**Issue by jiechen257** [jiechen257/langchain-demo#2]
```shell
$ npm run start

> langchain-ts-starter@1.0.0 start
> tsx -r dotenv/config src/index.ts

ReferenceError: Headers is not defined
    at createRequest (/Users/abm/Documents/personal/personal-project/langchain-demo/node_modules/.pnpm/langchain@0.0.39/node_modules/langchain/src/util/axios-fetch-adapter.js:273:19)
    at fetchAdapter (/Users/abm/Documents/personal/personal-project/langchain-demo/node_modules/.pnpm/langchain@0.0.39/node_modules/langchain/src/util/axios-fetch-adapter.js:196:19)
    at dispatchRequest (/Users/abm/Documents/personal/personal-project/langchain-demo/node_modules/.pnpm/axios@0.26.1/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/Users/abm/Documents/personal/personal-project/langchain-demo/node_modules/.pnpm/axios@0.26.1/node_modules/axios/lib/core/Axios.js:108:15)
    at Function.wrap (/Users/abm/Documents/personal/personal-project/langchain-demo/node_modules/.pnpm/axios@0.26.1/node_modules/axios/lib/helpers/bind.js:9:15)
    at <anonymous> (/Users/abm/Documents/personal/personal-project/langchain-demo/node_modules/.pnpm/openai@3.3.0/node_modules/openai/dist/common.js:149:22)
    at <anonymous> (/Users/abm/Documents/personal/personal-project/langchain-demo/node_modules/.pnpm/openai@3.3.0/node_modules/openai/dist/api.js:1740:133)
```

**Comment by jiechen257** [comment]
switch the node version to 18.x, 19.x, 20.x,via [langchainjs-readme](https://github.com/hwchase17/langchainjs)
